export const ACTION_TYPES = {
  ADD_GOODS_TO_BUCKET: 'ADD_GOODS_TO_BUCKET',
  REMOVE_GOODS_FROM_BUCKET: 'REMOVE_GOODS_FROM_BUCKET',
  INCREMENT_GOOD_COUNT: 'INCREMENT_GOOD_COUNT',
  DECREMENT_GOOD_COUNT: 'DECREMENT_GOOD_COUNT',
};
